### ISSUE TITLE
Improve ViewExt file

### ISSUE THREAD

**Issue by chemickypes** [manolodantonio/SLANG-library#1]
I'd like to siggest an improvement in ViewExt file.

You wrote this:
``` kotlin
fun View?.goneIf(shouldBeGone: Boolean): View? {
    this ?: return this
    if (shouldBeGone) gone() else visible()
    return this
}
```
but I think following function might be useful too
``` kotlin
fun View?.goneIf(shouldBeGoneBlock: () ->Boolean): View? {
    this ?: return this
    if (shouldBeGone.invoke()) gone() else visible()
    return this
}
```

In other words, you would improve your code adding the condition passed as result of high-level funcion.

**Comment by manolodantonio** [comment]
This is a great idea, i'll add it! - added in 0.1.2
