### ISSUE TITLE
Intent.start(context:Context) private. Why?

### ISSUE THREAD

**Issue by chemickypes** [manolodantonio/SLANG-library#2]
Why this method

``` kotlin
private fun Intent.start(context: Context): Boolean {
    return resolveActivity(context.packageManager)?.let {
        context.startActivity(this)
        true
    } ?: false
}
```

is private? it's very useful!

**Comment by manolodantonio** [comment]
Hi!
Thanks for the heads up. I was not sure resolveActivity returns true also in non-action intents. Tested with an internal activity navigation, it works. 
I updated the library!
